- name: Check if docker-compose.yml exists
  stat:
    path: /region2/docker-compose.yml
  register: compose_file

- name: Run Docker Compose Down
  shell: sudo docker compose down
  args:
    chdir: /region2
  when: compose_file.stat.exists

- name: Remove directory
  file:
    path: /region2           
    state: absent

- name: Create directory region2
  file:
    path: /region2       
    state: directory
    mode: '0755'

- name: Copy current directory
  copy:
    src: .
    dest: /region2  

- name: Run Docker Compose Build
  shell: sudo docker compose build --no-cache
  args:
    chdir: /region2

- name: Run Docker Compose Up
  shell: sudo docker compose up -d
  args:
    chdir: /region2
